"""empty message

Revision ID: 9229b7acd499
Revises: 
Create Date: 2020-10-10 14:18:32.093009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9229b7acd499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d_name', sa.String(length=64), nullable=True),
    sa.Column('g_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
