"""empty message

Revision ID: 09fef0b50c87
Revises: 
Create Date: 2020-09-17 17:44:33.825622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fef0b50c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=16), nullable=True),
    sa.Column('a_color', sa.String(length=16), nullable=True),
    sa.Column('a_weight', sa.Integer(), nullable=True),
    sa.Column('c_eat', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=16), nullable=True),
    sa.Column('a_color', sa.String(length=16), nullable=True),
    sa.Column('a_weight', sa.Integer(), nullable=True),
    sa.Column('d_eat', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogs')
    op.drop_table('cats')
    # ### end Alembic commands ###
