"""empty message

Revision ID: 5786295ca8ad
Revises: edc31ddb67b6
Create Date: 2020-10-09 16:12:41.584082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5786295ca8ad'
down_revision = 'edc31ddb67b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 's_phone')
    # ### end Alembic commands ###
