"""empty message

Revision ID: 8bdf9ac14d1c
Revises: c618bed97359
Create Date: 2020-09-14 17:33:15.242818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdf9ac14d1c'
down_revision = 'c618bed97359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_name', sa.String(length=16), nullable=True),
    sa.Column('c_legs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_name', sa.String(length=16), nullable=True),
    sa.Column('d_eat', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog')
    op.drop_table('cat')
    # ### end Alembic commands ###
