"""empty message

Revision ID: 57668a6fc390
Revises: e7ec800baeb1
Create Date: 2020-09-21 15:48:28.357713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57668a6fc390'
down_revision = 'e7ec800baeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cats_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats_1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('a_name', mysql.TINYTEXT(), nullable=True),
    sa.Column('a_height', mysql.TINYTEXT(), nullable=True),
    sa.Column('a_weight', mysql.TINYTEXT(), nullable=True),
    sa.Column('a_color', mysql.TINYTEXT(), nullable=True),
    sa.Column('a_detail', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('c_eat', mysql.TINYTEXT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
