"""empty message

Revision ID: e7ec800baeb1
Revises: 
Create Date: 2020-09-21 10:03:39.372959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ec800baeb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=16), nullable=True),
    sa.Column('a_height', sa.String(length=16), nullable=True),
    sa.Column('a_weight', sa.String(length=16), nullable=True),
    sa.Column('a_color', sa.String(length=16), nullable=True),
    sa.Column('a_detail', sa.Text(), nullable=True),
    sa.Column('c_eat', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=16), nullable=True),
    sa.Column('a_height', sa.String(length=16), nullable=True),
    sa.Column('a_weight', sa.String(length=16), nullable=True),
    sa.Column('a_color', sa.String(length=16), nullable=True),
    sa.Column('a_detail', sa.Text(), nullable=True),
    sa.Column('d_eat', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogs')
    op.drop_table('cats')
    # ### end Alembic commands ###
